name: MYCI
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  jobs1:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v1
      - run: echo ok
      - run: node -v
      - run: curl localhost:8080
  jobs2:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
